---
environment_variables:
  COLLABORA_VERSION: "23.05"
git:
  branch: main
triggers:
  cron: "@daily"
clean_workspace: true
pre_build_script:
  - echo ${COLLABORA_URL_FRAGMENT} > ./url_fragment
builders:
  - docker
docker_name: drive/collabora
docker_tags:
  - "${COLLABORA_VERSION}"
  - "latest"
docker_no_cache: true
